### Read all users
GET http://localhost:3002/users

### Create a new user
POST http://localhost:3002/users
Content-Type: application/json

{
    "username": "Zinedine Zidane",
    "email": "zizou.z5@legend.com",
    "password": "Zizou_Magic_Volley"
}

### Update a user
PUT http://localhost:3002/users/1
Content-Type: application/json

{
    "username": "Lionel Messi 555",
    "email": "lionel.messi@example.com",
    "password": "LM10_@InterM!2026"
}
