### Read all users (MongoDB)
GET http://localhost:3002/api/v2/users

### Create a new user (MongoDB)
POST http://localhost:3002/api/v2/users
Content-Type: application/json

{
  "username": "Kangxi",
  "role": "admin",
  "email": "kangxi@example.com",
  "password": "qingdynasty1661"
}

### Login user (MongoDB)
POST http://localhost:3002/api/v2/users/login
Content-Type: application/json

{
  "email": "kangxi@example.com",
  "password": "qingdynasty1661"
}

### Update a user (MongoDB) - ใช้ ID จริงของคังซีแล้ว
PUT http://localhost:3002/api/v2/users/6a0d6dde9f56e88888c06b7f
Content-Type: application/json

{
  "username": "Emperor Kangxi",
  "role": "user"
}

### Delete a user (MongoDB) - ใช้ ID จริงของคังซีแล้ว
DELETE http://localhost:3002/api/v2/users/6a0d6dde9f56e88888c06b7f